### PR TITLE
fix: build flags for samples

### PR DESCRIPTION
**Pull request by philcali**
### Motivation
- Fixes the flags set for samples
- Issue number: NA

#### Change summary
Please describe what changes are included in this pull request. 

#### Revision diff summary
If there is more than one revision, please explain what has been changed since the last revision.

### Testing
 **Is your change tested? If not, please justify the reason.**  
 **Please list your testing steps and test results.** 
- CI test run result: <link>

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shangabl** [comment]
Hello,

I was looking into why these workflows are all failing. We have recently made some changes to our CI/CD process and GitHub Secrets are not passed to workflows triggered by a PR from a fork. So, in order to pass our updated CI/CD workflow this PR will need to be made from a branch in our repository.  Could you push your feature branch to the repo and create a PR from that?

Thanks,
Shane

**Comment by philcali** [comment]
> Hello,
> 
> I was looking into why these workflows are all failing. We have recently made some changes to our CI/CD process and GitHub Secrets are not passed to workflows triggered by a PR from a fork. So, in order to pass our updated CI/CD workflow this PR will need to be made from a branch in our repository. Could you push your feature branch to the repo and create a PR from that?
> 
> Thanks, Shane

Is it possible for me to create a branch in the repo? I'll try this out.

**Comment by shangabl** [comment]
@philcali 

It should be! I think you should just be able to create a feature branch and push it to this repository... If that does not work then please let us know.

Thanks again!

Shane

**Comment by RogerZhongAWS** [comment]
merged to mainline, closing

**Pull request closed without merging**
